spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: shc1034813562
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 1.117.175.108
    password: shc1034813562

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true